export const destinationConstants = {
  SET_CURRENT_DESTINATION: "SET_CURRENT_DESTINATION",

  FETCH_DESTINATION_FILES_REQUEST: "FETCH_DESTINATION_FILES_REQUEST",
  FETCH_DESTINATION_FILES_SUCCESS: "FETCH_DESTINATION_FILES_SUCCESS",
  FETCH_DESTINATION_FILES_FAILURE: "FETCH_DESTINATION_FILES_FAILURE",
};
