export const fileConstants = {
  RENAME_REQUEST: "RENAME_REQUEST",
  RENAME_SUCCESS: "RENAME_SUCCESS",
  RENAME_FAILURE: "RENAME_FAILURE",

  DELETE_REQUEST: "DELETE_REQUEST",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILURE: "DELETE_FAILURE",

  MOVE_REQUEST: "MOVE_REQUEST",
  MOVE_SUCCESS: "MOVE_SUCCESS",
  MOVE_FAILURE: "MOVE_FAILURE",
};
