export const fileUploadConstants = {
  SET_UPLOAD_FILE: "SET_UPLOAD_FILE",

  UPLOADING: "UPLOADING",
  CANCELED: "CANCELED",
  FAILURE: "FAILURE",
  COMPLETED: "COMPLETED",

  SET_UPLOAD_PROGRESS: "SET_UPLOAD_PROGRESS",
  SUCCESS_UPLOAD_FILE: "SUCCESS_UPLOAD_FILE",
  CANCELED_UPLOAD_FILE: "CANCELED_UPLOAD_FILE",
  FAILURE_UPLOAD_FILE: "FAILURE_UPLOAD_FILE",
  RESET_UPLOAD_FILE: "RESET_UPLOAD_FILE",
};
