export const fileDownloadConstants = {
  FETCH_FILE_DOWNLOAD_REQUEST: "FETCH_FETCH_FILE_DOWNLOAD_REQUEST",
  FETCH_FILE_DOWNLOAD_SUCCESS: "FETCH_FILE_DOWNLOAD_SUCCESS",
  FETCH_FILE_DOWNLOAD_FAILURE: "FETCH_FILE_DOWNLOAD_FAILURE",
};
