export const folderConstants = {
  FETCH_CREATE_FOLDER_REQUEST: "FETCH_FETCH_CREATE_FOLDER_REQUEST",
  FETCH_CREATE_FOLDER_SUCCESS: "FETCH_CREATE_FOLDER_SUCCESS",
  FETCH_CREATE_FOLDER_FAILURE: "FETCH_CREATE_FOLDER_FAILURE",

  FETCH_ALL_FOLDERS_REQUEST: "FETCH_ALL_FOLDERS_REQUEST",
  FETCH_ALL_FOLDERS_SUCCESS: "FETCH_ALL_FOLDERS_SUCCESS",
  FETCH_ALL_FOLDERS_FAILURE: "FETCH_ALL_FOLDERS_FAILURE",

  SET_FOLDERS_FOR_BREADCRUMBS_FILE: "SET_FOLDERS_FOR_BREADCRUMBS_FILE",
};
