export const folderConstants = {
  FETCH_CREATE_FOLDER_REQUEST: "FETCH_FETCH_CREATE_FOLDER_REQUEST",
  FETCH_CREATE_FOLDER_SUCCESS: "FETCH_CREATE_FOLDER_SUCCESS",
  FETCH_CREATE_FOLDER_FAILURE: "FETCH_CREATE_FOLDER_FAILURE",
};
