export const modalConstants = {
  DELETE_FILE: "DELETE_FILE",
  RENAME_FILE: "RENAME_FILE",
  SHARE_FILE: "SHARE_FILE",
  MOVE_FILE: "MOVE_FILE",

  DELETE_FILES: "DELETE_FILES",
  MOVE_FILES: "MOVE_FILES",
};
